# -*- coding: utf-8 -*-
"""kpi_calculations.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SYawxOXUmhOsDBp9dEcwPkS0t_x-_ZIR
"""

import numpy as np
import pandas as pd

df = pd.read_excel('/content/ppc_campaign_performance_data.xlsx')

df

df.info()

df.describe()

df.isna().sum()

df.columns

pd.set_option('display.max_columns', None)

"""CTR (Click-Through Rate)
Indicates how well your ads are generating clicks from impressions.
"""

df['CTR'] = df['Clicks'] / df['Impressions']

"""CPC (Cost Per Click)
Shows how much you're paying for each click.
"""

df['CPC'] = df['Spend'] / df['Clicks']

"""CPA (Cost Per Acquisition)
Measures the cost to generate one conversion (customer).
"""

df['CPA'] = df['Spend'] / df['Conversions']

"""Conversion Rate
Shows the efficiency of clicks turning into conversions.
"""

df['Conversion_Rate'] = df['Conversions'] / df['Clicks']

"""ROAS (Return on Ad Spend)
Measures how much revenue you made for every dollar spent.
"""

df['ROAS'] = df['Revenue'] / df['Spend']

df

df.to_excel('campaign_analysis.xlsx', index=False)

